name: Add comment
on: [workflow_call]
jobs:
    comment:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            - name: add comment
              uses: mshick/add-pr-comment@v2
              with:
                message: |
                  Passed All CI checks

