name: Python application CI process
on:
    push:
        branches: ["master", "develop"]
    pull_request: 
        branches: ["master", "develop"]

jobs:
    build_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: setup python3.12
              uses: actions/setup-python@v4
              with:
                python-version: "3.12"

            - name: Add extra dependencies
              run: |
                pip install poetry
                poetry install --with dev

            - name: run pytest
              run : |
                poetry run pytest -sv

    code-analysis:
        needs: build_test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Python
              uses: actions/setup-python@v4
              with: 
                python-version: "3.12"

            - name: Add dependencies for python
              run: |
                pip install poetry
                poetry install --with dev

            - name: Generate code coverage report
              run: |
                poetry run coverage run -m pytest