name: Python application CI process
on:
    pull_request: 
        branches: ["master", "develop"]

jobs:
    build_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: setup python3.12
              uses: actions/setup-python@v4
              with:
                python-version: "3.12"

            - name: Add extra dependencies
              run: |
                pip install poetry
                poetry install --with dev

            - name: run pytest
              run : |
                poetry run pytest -sv

    code-analysis:
        # needs: build_test
        uses: ./.github/workflows/analysis.yaml

    comment:
      needs: 
        - build_test
        - code-analysis
      permissions:
          pull-requests: write
      uses: ./.github/workflows/add-comment.yaml